### ISSUE TITLE
ERROR: Repository error

### ISSUE THREAD

**Issue by ChristopherKing42** [felipec/git-remote-hg#17]
I try the command and this happens:
```
~/pychess$ git remote add -f i175 "hg::https://G.nius.ck@code.google.com/r/gniusck-175/"
Updating i175
ERROR: Repository error
error: Could not fetch i175
```
Other relevant info

Git 2.1.0 on Ubuntu with the latest version of git-remote-hg. I will leave the repo open for you to see if it is general or not.

**Comment by dmolesUC3** [comment]
I got this when I failed to provide a password in the https URL, which it looks like you're also doing, @TheKing42 ? When I provided a password, I got past this error, but then had other problems (which I filed as issue #34 ).

**Comment by TheKing42** [comment]
Wait, how do I specify a password in the url?

**Comment by dmolesUC3** [comment]
`https://[user]:[password]@example.org/...` -- see under "[Cloning HTTPS](https://github.com/felipec/git-remote-hg#cloning-https)" in the docs.

**Comment by fingolfin** [comment]
@TheKing42 It would still be interesting to get that stack trace -- since your repository is private, it is not that easy to reproduce the issue... although my guess is that this is indeed due to the password "missing" for the URL, and due to the way git-remote-hg runs mercurial (namely, disconnected from stdin), it has no way to ask you for the password. It would actually be nice if git-remote-hg could handle this; ideally, by bridging between mercurial and git-credential.

Alas, this seems somewhat difficult, given how git interfaces with git-remote-hg... it seems to me that it might require an extension to git itself? Not sure.

**Comment by TheKing42** [comment]
How would I give you a stack trace (and which issue would it be under?)

**Comment by fingolfin** [comment]
Contrary to what I believed, it seems quite possible to run "git credential" from inside git-remote-hg. So, there is hope for a proper fix :)

**Comment by fingolfin** [comment]
@TheKing42 To get the stack trace, edit git-remote-hg as described in my first comment on this issue, then re-run the clone. Anyway, it's probably indeed the case that this fails because there is no password given, and the way git-remote-hg works, the mercurial libs have no chance to ask you for the password.

I have begun work on some code that would improve this situation by calling git-credential -- this then can ask the user for username and/or password (as required), or (if configured by the user) look for the password in the OS X keychain, a .netrc file etc.

See https://github.com/fingolfin/git-remote-hg/tree/credentials (but it's hackish work in progress right now, so don't expect it to be usable right now (in particular, do NOT use it in production, it may cause git-remote-hg to get into a messed up state where you need to re-clone.)

**Comment by felipec** [comment]
@TheKing42 Did the URL with the password work?

**Comment by UrielSalomon** [comment]
Solved: supplying the username and password how dmolesUC3 said - works.
