### ISSUE TITLE
Force push to update a remote branch results in multiple heads

### ISSUE THREAD

**Issue by vincentbernat** [felipec/git-remote-hg#30]
When I modify a commit and force push the result to a remote branch, Bitbucket seems to be confused by the multiple heads that result from this. An associated PR is not updated with the content of the new head.

I was wondering if it would be sensible to strip the previous head when doing something like that. Or maybe, git-remote-hg is already able to do that?

Steps to reproduce:

 1. `git clone hg:...`
 2. `git checkout -b branches/my-new-feature`
 3. `git commit -m "New feature"`
 4. `git push origin branches/my-new-feature`
 5. `git commit --amend`
 6. `git push -f origin branches/my-new-feature`

**Comment by urkle** [comment]
This is similar to what I'm having in #36 as the repo I'm working against has multiple "default" heads for some reason (not created by me).   How does one even clean that up in Mercurial? (and why would an SCM system even allow that?!?!?)  The repo that I'm having issues with is  http://hg.libsdl.org/SDL

**Comment by felipec** [comment]
That's why you shouldn't push force in Mercurial. Mercurial's UI warns you about that.

What you are supposed to do (or somebody else), is use `hg merge` and merge the two heads.

You could stip the other head. Bitbucket has an option to do that.

But the best would be if you didn't `git push --force` in the first hand and merged directly from git in the first place.
