### ISSUE TITLE
"whole repo is rebased"

### ISSUE THREAD

**Issue by bukzor** [felipec/git-remote-hg#37]
I used git-remote-hg to author a patch for pylint, and everything worked flawlessly until the time came that upstream tried to merge: https://bitbucket.org/hpk42/pytest/pull-request/249/fix-handling-of-objects-with-non-ascii/activity

"""
Ronny Pfannschmidt DECLINED pull request #249:
uppon trying to pull local changes it seems like the repo was rebased please recreate the changes on a fresh repo
"""

Is this a bug, or simply an unsupported workflow?  Or, do I need to configure / use git-remote-hg differently git this to work?

**Comment by RonnyPfannschmidt** [comment]
its not the whole repo that is rebased, but i suspect a miss-interaaction when converting between hg/git, since git has no meta-data its hard to fix on the git side

**Comment by felipec** [comment]
The link doesn't work any more. I suspect what they meant was that the patch didn't apply in the latest head, that you needed to rebase your patch. Hard to tell without the patch, and the latest head it was supposed to apply to.

**Comment by RonnyPfannschmidt** [comment]
nope, when i tried to merge his patches, there was a bunch of duplicated/rebased history with slightly diffent metadata

**Comment by fingolfin** [comment]
While I didn't see the problematic commits, I have seen similar issues in the past. I'll describe a known problem scenario below; the issue here sounds a bit more complicated, but my guess would be that they are still related.

In a nutshell: git-remote-hg attempts to perform a 1-to-1 mapping between hg and git commits. However, as soon as two clones of the same repository (or two remotes in a single clone) are involved, this can break down: Either a single git commit now corresponds to two hg commits, or vice versa. The result is history duplication.

This in particular easily happens in a scenario where you have two hg remotes which you use in a triangular fashion: I.e. `origin` pointing to an upstream project on bitbucket, and `fork` pointing to your personal fork on bitbucket. You push to `fork`, make a pull request from that which is merged into `origin`, which you then pull. If this fails to roundtrip perfectly, you quickly end up in the situation described by @bukzor 


Here is a script which creates a single git commit corresponding to two hg commits:
```
rm -rf foo.hg foo.git
hg init foo.hg
cd foo.hg
echo A > A
hg add A
hg commit -m A
cd ..

git clone hg::foo.hg foo.git
cd foo.git
git remote add alt `git remote get-url origin`
git fetch --all

echo B > B
git add B
git commit -m B

git checkout -b branches/a
git push origin branches/a

git checkout -b branches/b
git push alt branches/b
```

Here is an example which creates two git commits corresponding to the same hg commits:
```
#!/bin/sh -ex

rm -rf foo.hg foo.git
hg init foo.hg
cd foo.hg
echo A > A
hg add A
hg commit -m A
cd ..

git clone hg::foo.hg foo.git
cd foo.git
git remote add alt `git remote get-url origin`
git fetch --all

echo B > B
git add B
git commit --author="test <>" -m B

git push origin
git fetch alt

echo "History for origin:"
git log --oneline origin/master

echo "History for alt:"
git log --oneline alt/master
```

Note that this is somewhat artificial, but I suspect that there are more "natural" ways to trigger it, as I experienced this "in the wild" a few times (but that was before I realized what was really going on, so to my regret back then I quickly decided the clone was broken, and simply deleted and then recreated it).

**Comment by felipec** [comment]
Those patches shouldn't have been sent if they were already in the repository, it's easy in Git to specify the range of commits you want to generate patches for.

I doubt the issues @fingolfin is talking about are the culprit here. But anyway, both of those issues can be fixed by storing Mercurial-specific metadata in Git extra data.

**Comment by fingolfin** [comment]
Again, you "doubt" -- how many hours did you spend on debugging similar problems? I spent many trying to debug similar issues last year, when I and come colleagues still used git-remote-hg heavily.

But of course it is indeed only a guess that the issue reported here is related. For without access to the affected clones, it's impossible to tell for sure either way *shrug*.

In the meantime, I don't think you can really fix this by adding more and more metadata. Or rather: You can perhaps fix these two particular instances. But for every fix you make, I think I can add another example that triggers a similar problem, by exploiting precisely that new metadata you added to fix the previous round of bugs. It's a game of whack-a-mole. (And in addition, interop between different git-remote-hg versions gets hampered, which shouldn't matter so much in the single-repos-with-multiple-hg-remotes scenario, but may very well matter if two or more people use git-remote-hg to interact with a single hg repository.

That said, there still might be some merit to trying that, because while I don't think that it can fully resolve the issue, it can *perhaps* make it less likely to occur in practical use (as opposed to artifical scripts which actively try to trigger them).

**Comment by felipec** [comment]
I'm just going to come out and say: I know more about both Git internals, and Mercurial internals, than you do.

You seem to have some need to prove me wrong. I'm not interested.

The issues people are experiencing are very likely caused by other things. I am interested in reproducing those issues reliably and fixing them (the fix will not involve this atomic thing). I am not interested in proving you wrong.

**Comment by fingolfin** [comment]
I think you are confusing discussions? I never claimed that this issue has anything to do with atomic writing of the marks file (that's indeed a completely unrelated issue, at least as far as I can tell).

And it may very well be that you know much more about the Git and Mercurial internals than me, I never argued for anything else; but again, I don't see how that is an argument for anything? Sounds like an "appeal to authority" fallacy. (I'll ignore the question how you could possibly know what I know about Git and Mercurial internals or not.)

I also don't care about proving you wrong. Indeed, I am mainly motivated by a desire to make git-remote-hg work reliably -- in the past mostly for my own good (as a heavy user of it), nowadays mostly to help others (as my usage has dropped considerably). I am honestly not sure how anything I said on this issue is about "proving you wrong"?

Anyway: I provided two scripts here which reproduce an issue of the kind reported here reliably. Yes, it's not clear whether this is the exact same as the original cause of the issue described here -- but given that the original data is gone, how do you propose we ever figure that out?

Perhaps, for the sake of other people who might want to help out with this, please at least document what conditions a script "reproducing those issues reliably" must satisfy in order to be deemed "acceptable"?

**Comment by felipec** [comment]
> but again, I don't see how that is an argument for anything? Sounds like an "appeal to authority" fallacy.

It's not a fallacy because it's not an argument. As I said, I'm not interested in proving you wrong.

The scripts you sent show an issue with metadata that can be fixed by using Git's extra metadata. The issue mentioned by @bukzor is unclear. The issue about atomic writing I bet is not experience in reality by anyone. And the real issues are due to concurrency or synchronization.

**Comment by fingolfin** [comment]
Again, I never said this has anything to do with atomic writes, so why do you keep bringing that up on this issue?

And why did you start talking about our relative knowledge about git and mercurial arguments if not to prove a point? Are you saying it just randomly popped into your mind and so you wrote it down? I don't believe that of course -- you just wanted to establish that you know better than me, and hence it's ok for you to dismiss whatever I write.

**Comment by felipec** [comment]
@fingolfin I'm removing your content-free comments. You are just wasting people's times. I'll spend my time working on the issues, not discussing with you.

**Comment by felipec** [comment]
If you have a more recent link of the issue please post it. Another option is that there was a date `git-remote-hg` wasn't handling correctly, and that cause the whole repository to appear differently. That should be fixed in the latest master branch.
