### ISSUE TITLE
Push to hg fails with KeyError in to_rev()

### ISSUE THREAD

**Issue by kk7ds** [felipec/git-remote-hg#85]
I have been using git-remote-hg successfully for a while, but I just tried to push something from git to hg and I get this:

```
dan@eagle ~/dev/repo.git$ git push orig py3:branches/py3                                                     ✭py3
Traceback (most recent call last):
  File "/users/dan/bin/git-remote-hg", line 1400, in <module>
    sys.exit(main(sys.argv))
  File "/users/dan/bin/git-remote-hg", line 1386, in main
    do_export(parser)
  File "/users/dan/bin/git-remote-hg", line 1174, in do_export
    parse_commit(parser)
  File "/users/dan/bin/git-remote-hg", line 883, in parse_commit
    p2 = mark_to_rev(merge_mark)
  File "/users/dan/bin/git-remote-hg", line 472, in mark_to_rev
    return marks.to_rev(mark)
  File "/users/dan/bin/git-remote-hg", line 185, in to_rev
    return str(self.rev_marks[mark])
KeyError: 9121
error: failed to push some refs to 'hg::~/dev/repo.hg'
```

I don't know what the problem is, and "9121" doesn't really mean much to me. Any help?

**Comment by IngeniousOne** [comment]
Hi, Dan!

In what repo are you trying to push your commit? If it is felipec`s repo,
then you should make *fork *of it in your account and then push your
changes to it. Then you should create a *merge request *from your repo to
felipec`s repo to integrate you improvements in main stock. After a review
mainteinters will make a decision if your code can be integrated or not.

Best regards, Vadim.

ср, 29 сент. 2021 г. в 06:19, Dan Smith ***@***.***>:

**Comment by kk7ds** [comment]
Heh, yeah, thanks I'm not that clueless :)

I'm using git-remote-hg to push back and forth between my own git and hg repos, and it's crashing, which is why I'm opening an issue here.

I've done some digging through git-remote-hg and it looks like git-fast-export was telling git-remote-hg about a merge commit which didn't seem to exist, which is why git-remote-hg was crashing like that. I've since run `git gc`, rebuilt my remote, and tried some other things that mean I can't reproduce this specific error. I think converting from a local remote to a remote over ssh (i.e. hg::ssh://...) has helped the situation a bit, although I don't really know why.

So, I'll leave this here and open in case @felipec wants to add some defensiveness around the mark lookup to at least offer a better error message. Maybe they also know why it could happen in the first place.

**Comment by felipec** [comment]
@kk7ds Sorry for the late reply. So what that error means is that git stored a mark that hg isn't aware of. The "marks" are how internally git commits and hg revisions are mapped to each other, the mark `9121` is a way to refer to a git commit.

It's inefficient to export all git commits all the time, so the commits that have already been exported are stored in a marks file: `.git/hg/origin/marks-git`, this is done by git's remote-helpers's framework, not git-remote-hg. Every mark there should map to a hg revision, and we (git-remote-hg) store the mapping in `.git/hg/origin/marks-hg`.

You are trying to push a git commit that has as a parent a hg revision that supposedly was already converted, but the code can't find it.

This is most likely caused by a previous crash: git exported a commit, stored the marks, and git-remote-hg din't generate the corresponding hg revision, so the marks are now out-of-sync.

You could try to find the mark `9121` in `marks-git` and delete it, or you could just delete the file and force everything to be exported again.

The proper way to fix the issue is running a tool I created: [marks-check](https://gist.githubusercontent.com/felipec/10551806/raw/9250d9110131aa05144be079caceecdd4e0f02be/git-marks-check), which will find the marks that aren't properly matched and remove them for you.

This should never happen though. I have a patch that should ensure that in the event of a crash the marks don't get out-of-sync, but I'll release that after v0.6 which should contain nothing but support for Python 3.

If you still have issues after running the marks-check tool, please reopen this.
