### ISSUE TITLE
Cloning error due to decode

### ISSUE THREAD

**Issue by ppjmoors** [felipec/git-remote-hg#90]
Hi,

I get this error message while cloning a hg repository:

_UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 51: invalid continuation byte
fatal: stream ends early_

Any tips on how to solve this?

**Comment by ppjmoors** [comment]
.

**Comment by felipec** [comment]
> I get this error message while cloning a hg repository:

Is this repository publicly available so I can try cloning it?

My guess is that some commit message or author contains non-utf-8 characters, which are not supported by git.

I am not sure what would be the best way to solve this, but I guess forcing a conversion to utf-8 even with glitches is preferable to failing completely.

**Comment by felipec** [comment]
`git remote-hg` is supposed to deal with all sorts of invalid author names, although maybe that particular one I've not fixed yet.

However, I don't think that's the issue here: `0xc4` is `Ä`.

Whatever the issue is, the repository still should be clonable. The two approaches to do that are 1) create an author map list (so far there hasn't been a need to implement that), and 2) have some automagic rules that convert whatever is there.

If you can find the commit that causes the problem, I can find a way to workaround that in the code.

Feel free to reopen if you have more information.
